(async () => {
    const assert = (condition, message) => { if (!condition) throw new Error(message); };
    const tick = (ms = 20) => new Promise(resolve => setTimeout(resolve, ms));
    const waitFor = async (condition, description) => {
        for (let i = 0; i < 700; i++) { if (condition()) return; await tick(); }
        throw new Error("Timed out: " + description);
    };
    const frame = document.getElementById("appFrame");
    const mobile = new URLSearchParams(location.search).has("mobile");
    frame.style.width = mobile ? "390px" : "100%";
    let page, doc, copied = "";
    const state = async () => (await fetch("/__stage8_state")).json();
    const ready = () => !doc.getElementById("newChatButton").disabled;
    const active = () => Number(doc.querySelector('#conversationList [aria-current="page"]')?.dataset.conversationId) || null;
    const input = () => doc.getElementById("messageInput");
    const setInput = text => { input().value = text; input().setSelectionRange(text.length, text.length); input().dispatchEvent(new page.Event("input", { bubbles: true })); };
    const key = (name, opts = {}) => {
        const event = new page.KeyboardEvent("keydown", { key: name, bubbles: true, cancelable: true, ...opts });
        input().dispatchEvent(event);
        return event;
    };
    const sidebar = () => { if (mobile) doc.getElementById("menuButton").click(); };
    const newChat = () => { sidebar(); doc.getElementById("newChatButton").click(); };
    const send = async text => { setInput(text); await page.sendMessage(); };
    const rows = () => [...doc.querySelectorAll(".message[data-message-id]")];
    const action = (row, name) => [...row.querySelectorAll(".message-actions button")].find(button => button.textContent === name);
    const open = async (url = "/?test=" + Date.now(), waitUntilReady = true) => {
        const loaded = new Promise(resolve => frame.addEventListener("load", resolve, { once: true }));
        frame.src = url;
        await loaded;
        page = frame.contentWindow;
        doc = frame.contentDocument;
        if (waitUntilReady) await waitFor(ready, "initialization");
        Object.defineProperty(page.navigator, "clipboard", { configurable: true, value: { writeText: async text => { copied = text; } } });
    };
    try {
        // Real textarea editing must work even while startup requests stall.
        for (const suffix of ["", "?messages=1"]) {
            await open("/__stage8_slow" + suffix, false);
            await waitFor(() => page.releaseHistory, "delayed startup request");
            assert(!input().disabled && !input().closest("[inert]"), "Startup blocks typing");
            const rect = input().getBoundingClientRect();
            assert(doc.elementFromPoint(rect.x + rect.width / 2, rect.y + rect.height / 2) === input(), "Composer is covered by another element");
            input().focus();
            assert(doc.activeElement === input(), "Composer cannot receive focus");
            assert(doc.execCommand("insertText", false, "Typing while history loads"), "Native text insertion failed");
            assert(input().value === "Typing while history loads", "Startup discarded typed text");
            page.releaseHistory();
            await waitFor(ready, "delayed startup finished");
            assert(input().value === "Typing while history loads" && active() === null, "Late history overwrote the draft or selected another chat");
            setInput("");
        }
        await open("/__stage8_slow", false);
        input().focus();
        doc.execCommand("insertText", false, "Draft survives timeout");
        await waitFor(ready, "startup request timeout");
        assert(input().value === "Draft survives timeout" && !input().disabled, "Timeout lost or locked the draft");
        assert(doc.getElementById("storageNotice").textContent.includes("too long"), "Timeout did not explain the failure");
        setInput("");
        await open();
        assert((await state()).conversations.length === 0, "Startup created a chat");
        setInput("- First");
        input().focus();
        assert(key("Enter").defaultPrevented && input().value === "- First\n- ", "List continuation failed");
        doc.execCommand("undo");
        assert(input().value === "- First", "Smart edit lost native undo");
        doc.execCommand("redo");
        assert(input().value === "- First\n- ", "Smart edit lost native redo");
        key("Backspace");
        assert(input().value === "- First\n", "Empty item backspace did not exit list");
        setInput("9. One"); key("Enter");
        assert(input().value === "9. One\n10. ", "Numbered continuation failed");
        setInput("- nested"); key("Tab");
        assert(input().value === "  - nested", "Tab indentation failed");
        key("Tab", { shiftKey: true });
        assert(input().value === "- nested", "Unindent failed");
        setInput("```py\n    print(1)"); key("Enter");
        assert(input().value.endsWith("\n    "), "Code indentation not preserved");
        key("Enter");
        assert(input().value.endsWith("```\n"), "Empty code line did not exit fence");
        setInput("first second"); input().setSelectionRange(5, 12); key("Enter", { shiftKey: true });
        assert(input().value === "first\n", "Selection replacement corrupted text");
        setInput("- first\n- second"); input().setSelectionRange(0, input().value.length); key("Tab");
        assert(input().value === "  - first\n  - second" && input().selectionStart === 2 && input().selectionEnd === input().value.length, "Indent lost selected text");
        setInput("IME text");
        input().dispatchEvent(new page.CompositionEvent("compositionstart"));
        assert(!key("Enter", { isComposing: true }).defaultPrevented, "Composing Enter intercepted");
        input().dispatchEvent(new page.CompositionEvent("compositionend"));
        assert(!key("Enter").defaultPrevented, "Composition-ending Enter submitted");
        await tick(80);
        assert((await state()).conversations.length === 0, "IME created a conversation");
        setInput("Prose");
        assert(!key("Tab").defaultPrevented, "Normal Tab focus navigation intercepted");
        input().dispatchEvent(new page.InputEvent("beforeinput", { inputType: "insertLineBreak", bubbles: true, cancelable: true }));
        assert(input().value === "Prose\n", "Touch return should insert newline");
        setInput("x\n".repeat(40));
        assert(input().clientHeight <= 181 && input().scrollHeight > input().clientHeight && page.getComputedStyle(input()).overflowY === "auto", "Composer height not capped");
        setInput("small");
        assert(input().clientHeight < 80, "Composer did not shrink");
        await send("My secret word is pineapple");
        const a = active();
        assert(a && input().value === "", "Accepted send did not clear draft");
        setInput("Draft A"); input().setSelectionRange(2, 5); page.saveDraft();
        newChat();
        setInput("New-chat draft");
        await page.openConversation(a);
        assert(input().value === "Draft A" && input().selectionStart === 2 && input().selectionEnd === 5, "Conversation draft or selection lost");
        newChat();
        assert(input().value === "New-chat draft", "New-chat draft lost");
        await send("What is my secret word?");
        const b = active();
        assert(!rows().at(-1).textContent.includes("pineapple"), "Conversation context leaked");
        setInput("Draft B");
        await page.openConversation(a);
        assert(input().value === "Draft A", "Switching erased draft A");
        await send("Show Markdown <img src=x onerror=alert(1)>");
        const before = (await state()).messages[a];
        const assistant = rows().at(-1);
        assert(assistant.querySelector("h1") && assistant.querySelector("table") && assistant.querySelector("pre code"), "Markdown rendering lost");
        assert(!assistant.querySelector("img,script,iframe") && !page.__markdownXss, "Unsafe Markdown survived");
        assert(!rows().at(-2).querySelector(".message-content img"), "User text interpreted as HTML");
        action(assistant, "Copy").click(); await tick();
        assert(copied === before.at(-1).content && action(assistant, "Copied"), "Assistant copy lost raw Markdown or feedback");
        action(rows()[0], "Copy").click(); await tick();
        assert(copied === before[0].content, "User copy failed");
        action(assistant, "👍").click();
        await waitFor(() => action(assistant, "👍").getAttribute("aria-pressed") === "true", "feedback persistence");
        assert((await state()).messages[a].at(-1).feedback === 1, "Feedback not saved");
        setInput("Keep this draft while editing");
        const edit = async row => {
            action(row, "Edit").click();
            await waitFor(() => doc.querySelector(".message-edit textarea"), "inline edit");
            return doc.querySelector(".message-edit textarea");
        };
        const submitEdit = async text => {
            const editor = doc.querySelector(".message-edit textarea");
            editor.value = text;
            doc.querySelector(".message-edit").requestSubmit();
            await waitFor(() => ready() && !doc.querySelector(".message-edit"), "edited response");
        };
        const version = (row, direction) => row.querySelector(`[aria-label="${direction} version"]`);
        const choose = async (row, direction) => {
            version(row, direction).click();
            await waitFor(ready, "branch switch");
            // Branch cancellation first yields one microtask before loading.
            await tick(80);
            await waitFor(ready, "branch loaded");
        };
        assert((await edit(rows()[0])).value === before[0].content, "Edit did not prefill original");
        [...doc.querySelectorAll(".message-edit button")].find(control => control.textContent === "Cancel").click();
        assert(input().value === "Keep this draft while editing" && !doc.querySelector(".message-edit"), "Cancel edit lost composer draft");
        await edit(rows()[0]);
        await submitEdit(before[0].content);
        assert((await state()).trees[a].messages.length === before.length, "Unchanged edit created a branch");
        await edit(rows()[0]);
        await submitEdit("Edited first question");
        let snapshot = await state();
        assert(active() === a && snapshot.messages[a].length === 2, "Edit failed to select a sibling path");
        assert(snapshot.trees[a].messages.length === before.length + 2, "Edit duplicated prefix or lost original rows");
        assert(snapshot.trees[a].messages[0].content === before[0].content, "Editing rewrote original history");
        assert(rows()[0].querySelector(".branch-position").textContent === "2 / 2", "User branch counter missing");
        assert(input().value === "Keep this draft while editing", "Edit lost composer draft");
        await send("Descendant of edited user");
        const editedPath = (await state()).messages[a].map(message => message.id);
        await choose(rows()[0], "Previous");
        assert(rows().length === before.length && rows()[0].textContent.includes(before[0].content), "Original descendants lost");
        await choose(rows()[0], "Next");
        assert(JSON.stringify((await state()).messages[a].map(message => message.id)) === JSON.stringify(editedPath), "User sibling descendants mixed");
        await choose(rows()[0], "Previous");
        action(rows()[1], "Regenerate").click();
        await tick(80); await waitFor(ready, "regenerate branch");
        snapshot = await state();
        assert(active() === a && snapshot.messages[a].length === 2 && snapshot.messages[a][0].id === before[0].id, "Regeneration changed its parent user");
        assert(rows()[1].querySelector(".branch-position").textContent === "2 / 2", "Assistant branch counter missing");
        await send("Descendant of second assistant");
        const regeneratedPath = (await state()).messages[a].map(message => message.id);
        await choose(rows()[1], "Previous");
        assert(rows().length === before.length && rows().at(-2).textContent.includes("Show Markdown"), "Original assistant descendants lost");
        await send("Continue first assistant separately");
        assert(!(await state()).model_calls.at(-1).messages.some(message => message.content === "Descendant of second assistant"), "Sibling leaked into model context");
        await choose(rows()[1], "Next");
        assert(JSON.stringify((await state()).messages[a].map(message => message.id)) === JSON.stringify(regeneratedPath), "Assistant branches mixed descendants");
        await open();
        assert(JSON.stringify((await state()).messages[a].map(message => message.id)) === JSON.stringify(regeneratedPath), "Reload lost branch selection");
        newChat();
        await send("Fail once browser test");
        const failedId = active();
        snapshot = await state();
        const failedRows = snapshot.messages[failedId];
        assert(failedRows.at(-1).status === "error" && rows().at(-1).textContent.includes("incomplete"), "Failure not saved and labeled");
        action(rows().at(-1), "Retry").click();
        await waitFor(() => ready() && !doc.querySelector(".message-state"), "retry completion");
        snapshot = await state();
        assert(snapshot.messages[failedId].length === 2 && snapshot.messages[failedId][1].id !== failedRows[1].id && snapshot.trees[failedId].messages[1].status === "error", "Retry rewrote the failed response");
        newChat();
        setInput("Stop after partial text");
        const sending = page.sendMessage();
        await waitFor(() => doc.querySelector(".message-content h2")?.textContent === "Partial reply", "partial response");
        assert(!ready() && !doc.getElementById("stopButton").hidden, "Stop unavailable during generation");
        assert([...doc.querySelectorAll('.message-actions button[data-availability="idle"]')].every(button => button.disabled), "Conflicting message actions enabled");
        const userCopy = action(rows()[0], "Copy");
        assert(!userCopy.disabled, "User Copy disabled during streaming");
        userCopy.click();
        await tick();
        assert(copied === "Stop after partial text" && userCopy.textContent === "Copied", "User copy or feedback failed during streaming");
        assert(!ready(), "Copy interrupted generation");
        doc.getElementById("stopButton").click();
        await sending;
        const stoppedId = active();
        snapshot = await state();
        assert(ready() && snapshot.messages[stoppedId][1].status === "stopped" && snapshot.messages[stoppedId][1].content === "## Partial reply", "Stop lost partial response or lock");
        assert(rows().at(-1).querySelector("h2") && action(rows().at(-1), "Regenerate"), "Stopped Markdown/regenerate missing");
        setInput("Retained stopped-chat draft");
        await open();
        assert(active() === stoppedId && rows().at(-1).textContent.includes("Stopped") && input().value === "Retained stopped-chat draft", "Stopped response or draft lost after reload: " + JSON.stringify({active: active(), stoppedId, text: rows().at(-1)?.textContent, draft: input().value, notice: doc.getElementById("storageNotice").textContent}));
        newChat();
        setInput("Wait before tokens");
        const waiting = page.sendMessage();
        await waitFor(() => doc.querySelector(".message-state")?.textContent.includes("Generating"), "waiting response");
        const waitingCopy = action(rows()[0], "Copy");
        assert(!waitingCopy.disabled, "User Copy disabled before the first token");
        waitingCopy.click();
        await tick();
        assert(copied === "Wait before tokens", "Copy before the first token failed");
        doc.getElementById("stopButton").click(); await waiting;
        assert((await state()).messages[active()][1].status === "stopped", "Stop before tokens failed");
        // Edit directly interrupts the stream, without a separate Stop click.
        newChat();
        setInput("Stop after partial edit race");
        const editRun = page.sendMessage();
        await waitFor(() => rows().at(-1)?.querySelector("h2"), "edit race partial");
        const editedStreamingId = active();
        const streamingAssistant = Number(rows().at(-1).dataset.messageId);
        assert(!action(rows()[0], "Edit").disabled, "Edit disabled during generation");
        await edit(rows()[0]);
        await editRun;
        snapshot = await state();
        assert(snapshot.trees[editedStreamingId].messages.find(message => message.id === streamingAssistant).status === "stopped", "Edit failed to stop old response");
        await submitEdit("New edited answer");
        assert(!rows().at(-1).textContent.includes("Partial reply"), "Cancelled tokens leaked into edited response");
        await choose(rows()[0], "Previous");
        assert(rows().at(-1).textContent.includes("Partial reply") && rows().at(-1).textContent.includes("Stopped"), "Original partial branch was lost");
        // Regenerate during streaming cancels one sibling and reserves another.
        action(rows().at(-1), "Regenerate").click();
        await waitFor(() => !ready() && rows().at(-1)?.querySelector("h2"), "regenerated partial");
        await tick(100);
        const firstRetryId = Number(rows().at(-1).dataset.messageId);
        action(rows().at(-1), "Regenerate").click();
        await waitFor(() => Number(rows().at(-1)?.dataset.messageId) !== firstRetryId && !ready(), "regenerate while generating");
        await waitFor(() => rows().at(-1)?.querySelector("h2"), "next partial");
        snapshot = await state();
        assert(snapshot.trees[editedStreamingId].messages.find(message => message.id === firstRetryId).status === "stopped", "Regenerate erased or failed to stop preceding sibling");
        // Switching a branch while streaming also waits for cancellation.
        const switchingId = Number(rows().at(-1).dataset.messageId);
        await choose(rows()[0], "Next");
        snapshot = await state();
        assert(snapshot.trees[editedStreamingId].messages.find(message => message.id === switchingId).status === "stopped", "Branch switch failed to cancel");
        assert(rows()[0].textContent.includes("New edited answer") && !rows().at(-1).textContent.includes("Partial reply"), "Switch mixed branch content");
        // Latest intent wins: Edit then switch during the same active stream.
        await choose(rows()[0], "Previous");
        action(rows().at(-1), "Regenerate").click();
        await waitFor(() => !ready() && rows().at(-1)?.querySelector("h2"), "rapid action partial");
        await tick(100);
        action(rows()[0], "Edit").click();
        version(rows()[0], "Next").click();
        await tick(80); await waitFor(ready, "rapid edit/switch cancellation");
        assert(!doc.querySelector(".message-edit") && rows()[0].textContent.includes("New edited answer"), "Stale edit won over a newer branch switch");
        // Inject a stale UUID into the real SSE stream; it must be ignored.
        const nativeFetch = page.fetch.bind(page);
        page.fetch = async (url, options) => {
            const response = await nativeFetch(url, options);
            if (url !== "/chat" || !response.ok) return response;
            const transform = new page.TransformStream({
                start(controller) {
                    controller.enqueue(new page.TextEncoder().encode('data: {"type":"delta","content":"STALE_TOKEN","generation_id":"cancelled-uuid"}\n\n'));
                }, transform(chunk, controller) { controller.enqueue(chunk); }
            });
            return new page.Response(response.body.pipeThrough(transform), { status: response.status, headers: response.headers });
        };
        await send("Verify stale stream protection");
        page.fetch = nativeFetch;
        assert(!doc.getElementById("chat").textContent.includes("STALE_TOKEN"), "Stale request token rendered");
        // Search and deletion remain functional after branching/cancellation.
        sidebar();
        const search = doc.getElementById("chatSearch");
        search.value = "pineapple"; search.dispatchEvent(new page.Event("input", { bubbles: true }));
        await waitFor(() => doc.querySelector(".search-hit mark"), "search after branching");
        doc.querySelector(".search-hit").click();
        await waitFor(ready, "search open");
        assert(doc.activeElement.classList.contains("search-target"), "Search message navigation lost");
        sidebar(); doc.getElementById("clearSearch").click();
        for (const item of (await state()).conversations) {
            sidebar();
            const row = doc.querySelector(`#conversationList [data-conversation-id="${item.id}"]`).closest(".conversation-row");
            row.querySelector("summary").click();
            [...row.querySelectorAll(".conversation-actions button")].find(button => button.textContent === "Delete").click();
            assert(doc.getElementById("conversationDialog").open, "Delete confirmation absent");
            doc.getElementById("conversationActionForm").requestSubmit();
            await waitFor(() => ready() && !doc.getElementById("conversationDialog").open, "delete branch");
        }
        assert(active() === null && doc.querySelector(".conversation-list-empty"), "Deletion empty state broken");
        assert(doc.documentElement.scrollWidth <= page.innerWidth + 1, "Mobile layout overflow");
        await fetch("/__stage8_result", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ result: "PASS", viewport: [page.innerWidth, page.innerHeight], checks: "Composer undo/redo, IME, lists, code, selection, resizing, drafts; copy, feedback, edit/regenerate branches, retry, cancellation before/after tokens, persistence, Markdown, isolation, search, delete" }) });
    } catch (error) {
        await fetch("/__stage8_release", { method: "POST" });
        await fetch("/__stage8_result", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ result: "FAIL", error: error.stack }) });
    }
})();
