(async () => {
    const assert = (ok, message) => { if (!ok) throw new Error(message); };
    const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
    const wait = async (predicate, label) => {
        for (let i = 0; i < 500; i++) { if (predicate()) return; await sleep(20); }
        throw new Error("Timeout: " + label);
    };
    const mobile = new URLSearchParams(location.search).has("mobile");
    const frame = document.getElementById("appFrame");
    frame.style.width = mobile ? "390px" : "100%";
    let page, doc;
    const report = result => fetch("/__stage8_result", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(result) });
    try {
        const loaded = new Promise(resolve => frame.addEventListener("load", resolve, { once: true }));
        frame.src = "/?response-check=1";
        await loaded;
        page = frame.contentWindow; doc = frame.contentDocument;
        await wait(() => !doc.getElementById("newChatButton").disabled, "startup");
        let copied;
        Object.defineProperty(page.navigator, "clipboard", { configurable: true, value: { writeText: async text => { copied = text; } } });
        const make = text => { const node = page.addMessage("AI", ""); page.renderAssistantMessage(node, text); return node; };
        const short = make("A short reply.");
        assert(short.clientHeight < 100 && short.tabIndex === -1 && !short.classList.contains("response-overflow"), "Short replies constrained unnecessarily");
        const source = 'def hello(name):\n\tprint("Hello", name)  \n\n# <img src=x onerror=alert(1)>';
        const fence = String.fromCharCode(96).repeat(3);
        const markdown = "# A heading\n\n**Bold**\n\n- One\n- Two\n\n| A | B |\n|---|---|\n|1|2|\n\n" + fence + "python\n" + source + "\n" + fence + "\n\n" + fence + "javascript\nconst x = 42;\n" + fence + "\n\n" + fence + "css\nbody { color: red; }\n" + fence + "\n\n" + fence + "made-up\n<unsafe>plain & literal</unsafe>\n" + fence + "\n\n<img src=x onerror='window.__unsafe=true'>";
        const codeReply = make("");
        const originalHighlight = page.Prism.highlight;
        let highlights = 0;
        page.Prism.highlight = (...args) => { highlights++; return originalHighlight(...args); };
        for (let i = 0; i < 3; i++) page.renderAssistantMessage(codeReply, markdown, { final: false });
        assert(highlights === 0 && !codeReply.querySelector(".token"), "Highlighted every streamed token");
        page.renderAssistantMessage(codeReply, markdown);
        assert(highlights === 3 && codeReply.querySelector(".token.keyword"), "Known languages were not highlighted");
        page.renderAssistantMessage(codeReply, markdown);
        assert(highlights === 3, "Final code highlight cache was not used");
        const blocks = codeReply.querySelectorAll(".code-block");
        assert(blocks.length === 4 && blocks[0].querySelector("code").textContent === source, "Code whitespace or multiple blocks lost");
        assert(blocks[3].querySelector("code").textContent === "<unsafe>plain & literal</unsafe>" && !blocks[3].querySelector(".token"), "Unknown language fallback broken");
        assert(codeReply.querySelectorAll("table tbody tr").length === 1 && codeReply.querySelectorAll("ul li").length === 2, "Surrounding Markdown lost");
        assert(!codeReply.querySelector("img, script") && !page.__unsafe, "Unsafe Markdown executed");
        blocks[0].querySelector(".copy-code").click();
        await wait(() => copied === source && blocks[0].querySelector(".copy-code").textContent === "Copied", "copy code");
        assert(blocks[0].querySelector(".copy-code").textContent === "Copied", "Copy confirmation missing");
        await sleep(1850);
        assert(blocks[0].querySelector(".copy-code").textContent === "Copy code", "Copy confirmation did not reset");
        page.navigator.clipboard.writeText = async () => { throw new Error("Denied"); };
        blocks[0].querySelector(".copy-code").click();
        await sleep(30);
        assert(page.getSelection().toString() === source, "Clipboard-denied fallback did not select exact source");
        page.getSelection().removeAllRanges();
        const incomplete = make("");
        page.renderAssistantMessage(incomplete, fence + "python\ndef unfinished(", { final: false });
        assert(incomplete.querySelector("code").textContent === "def unfinished(", "Incomplete fence lost text");
        page.Prism.highlight = () => '<img src=x onerror=alert(1)><span class="token keyword">safe</span>';
        const hostile = make(fence + "python\nunsafe_result = True\n" + fence);
        assert(!hostile.querySelector("img") && hostile.querySelector(".token"), "Highlighter output was not sanitized");
        page.Prism.highlight = originalHighlight;
        const longSource = Array.from({ length: 70 }, (_, i) => "print(" + i + ") # " + "x".repeat(150)).join("\n");
        const longMarkdown = fence + "python\n" + longSource + "\n" + fence + "\n\nEnd.";
        const long = make(longMarkdown);
        const outer = doc.getElementById("conversation");
        await sleep(50);
        assert(long.clientHeight >= 350 && long.clientHeight <= 450 && long.scrollHeight > long.clientHeight, "Long response is not capped at 400px");
        assert(long.tabIndex === 0 && long.getAttribute("role") === "region", "Long reply is not keyboard accessible");
        outer.scrollTop = 0; long.scrollTop = 0;
        const wheel = deltaY => new page.WheelEvent("wheel", { deltaY, bubbles: true, cancelable: true });
        long.dispatchEvent(new page.PointerEvent("pointerenter", { pointerType: "mouse" }));
        long.dispatchEvent(wheel(90));
        assert(long.scrollTop === 0 && outer.scrollTop > 0, "Inactive response captured the mouse wheel");
        long.dispatchEvent(new page.PointerEvent("pointerleave"));
        await sleep(920);
        assert(!long.classList.contains("inner-scroll-active"), "Early pointer leave did not cancel hover timer");
        long.dispatchEvent(new page.PointerEvent("pointerenter", { pointerType: "mouse" }));
        await sleep(300);
        assert(!long.classList.contains("inner-scroll-active"), "Hover captured too early");
        await sleep(620);
        assert(page.getComputedStyle(long).overflowY === "auto" && page.getComputedStyle(long).overscrollBehaviorY === "contain", "Delayed scroll activation failed");
        const beforeOuter = outer.scrollTop;
        long.dispatchEvent(wheel(120));
        assert(long.scrollTop === 120 && outer.scrollTop === beforeOuter, "Active inner wheel scrolled the main chat");
        const pre = long.querySelector("pre");
        pre.scrollLeft = 100;
        assert(pre.scrollLeft === 100 && pre.scrollWidth > pre.clientWidth, "Horizontal code scroll missing");
        page.renderAssistantMessage(long, longMarkdown + "\n\nNew content", { final: false });
        assert(long.scrollTop === 120 && long.querySelector("pre").scrollLeft === 100, "Streaming reset inner/code reading positions");
        long.dispatchEvent(wheel(40));
        assert(long.scrollTop === 160, "Streaming attached duplicate wheel listeners");
        long.dispatchEvent(new page.PointerEvent("pointerleave"));
        assert(!long.classList.contains("inner-scroll-active"), "Pointer leave did not deactivate");
        long.focus({ preventScroll: true });
        assert(page.getComputedStyle(long).overflowY === "auto" && page.getComputedStyle(long).outlineStyle !== "none", "Keyboard focus does not activate scrolling visibly");
        long.dispatchEvent(new page.KeyboardEvent("keydown", { key: "Escape", bubbles: true }));
        assert(doc.activeElement === outer && !long.classList.contains("inner-scroll-active"), "Escape did not return to primary scroll area");
        long.dispatchEvent(new page.PointerEvent("pointerdown", { pointerType: "touch", bubbles: true }));
        assert(page.getComputedStyle(long).overflowY === "auto", "Direct touch did not activate scrolling");
        const oldBg = page.getComputedStyle(long.querySelector("pre")).backgroundColor;
        doc.documentElement.dataset.codeTheme = "light";
        assert(page.getComputedStyle(long.querySelector("pre")).backgroundColor !== oldBg, "Light code theme unavailable");
        delete doc.documentElement.dataset.codeTheme;
        const prism = page.Prism;
        page.Prism = undefined;
        const fallback = make(fence + "python\nprint('plain fallback')\n" + fence);
        assert(fallback.querySelector("code").textContent === "print('plain fallback')", "Missing-library plain text fallback failed");
        page.Prism = prism;
        const input = doc.getElementById("messageInput");
        input.value = "Long response test";
        const sending = page.sendMessage();
        await wait(() => doc.querySelector(".response-overflow code")?.textContent.includes("stream_line"), "long test prefix");
        const streamed = doc.querySelector(".response-overflow");
        const retainedId = streamed.closest("article").dataset.messageId;
        assert(!streamed.querySelector(".token"), "Incomplete stream highlighted early");
        streamed.focus({ preventScroll: true });
        streamed.dispatchEvent(wheel(110));
        const savedScroll = streamed.scrollTop;
        await fetch("/__stage8_release", { method: "POST" });
        await sending;
        const settled = doc.querySelector('[data-message-id="' + retainedId + '"] .response-body');
        assert(settled === streamed, "Generation replaced the assistant container");
        assert(settled.scrollTop === savedScroll && settled.querySelector(".token"), "Final highlighting moved the reader or was missing");
        assert(doc.activeElement === settled, "Generation stole keyboard focus from the reader");
        const latest = doc.getElementById("scrollToBottom");
        assert(!latest.hidden && latest.textContent.includes("New content below"), "New content indicator missing while reading");
        latest.click();
        assert(settled.scrollHeight - settled.scrollTop - settled.clientHeight < 3 && latest.hidden, "Latest response button failed");
        assert(doc.documentElement.scrollWidth <= page.innerWidth + 1, "Horizontal page overflow on mobile");
        await fetch("/__stage8_hold", { method: "POST" });
        input.value = "Long response test again";
        const secondSending = page.sendMessage();
        await wait(() => {
            const bodies = [...doc.querySelectorAll(".response-body")];
            return bodies.length === 2 && bodies.at(-1).textContent.includes("stream_line");
        }, "second streamed response");
        outer.dispatchEvent(wheel(-400));
        outer.scrollTop = 0;
        outer.dispatchEvent(new page.Event("scroll"));
        await sleep(80);
        assert(outer.scrollTop === 0, "Main reader was immediately pulled down");
        await fetch("/__stage8_release", { method: "POST" });
        await secondSending;
        assert(outer.scrollTop === 0 && !latest.hidden && latest.textContent.includes("New content"), "Streaming completion fought main chat scrolling");
        latest.click();
        assert(outer.scrollHeight - outer.scrollTop - outer.clientHeight < 3, "Main latest control did not scroll down");
        const id = Number(doc.querySelector('#conversationList [aria-current="page"]').dataset.conversationId);
        await fetch("/conversations/" + id, { method: "DELETE" });
        await report({ result: "PASS", viewport: [page.innerWidth, page.innerHeight], checks: "short/long layout; delayed/cancelled hover; wheel routing; touch activation; keyboard; horizontal code + vertical reply; clipboard; language fallback; final cached highlighting; sanitization; reading position/container identity through streaming; new content/latest control; light/dark code palette" });
    } catch (error) {
        await fetch("/__stage8_release", { method: "POST" }).catch(() => {});
        await report({ result: "FAIL", error: error.stack });
    }
})();